### PR TITLE
Project Lifeguard blogpost

### PR DESCRIPTION
**Pull request by Beanow**
image

### CODE REVIEW

**Comment by nothingismagick** [comment]
I don't like the text over the image that has text in it.

**Comment by Beanow** [comment]
Me either. Though it is caused in the screenshot by having the tablet-ish 1024 width.
On 2560 (1440p) it looks like:
image

And 1920 (1080p)
image

**Comment by Beanow** [comment]
I could switch it for the one I use later on.
image

image

**Comment by nothingismagick** [comment]
That doesn't really address the concern I have. I would probably put a horizontal bar of a transparent gray behind the text.

**Comment by nothingismagick** [comment]
Yeah, I think that this is the better approach

**Review by nothingismagick — APPROVED** [review]
go for it

**Pull request merged**
